### ISSUE TITLE
How to manage external dependencies when going through a real coq project?

### ISSUE THREAD

**Issue by brando90** [HazardousPeach/coq_serapy#5]
Hi, 

If I want to use coq_serapy to create a data set from real coq projects, how do I make sure I install the right dependencies for the current coq project? And then how do I make sure I uninstall them automatically (or start clean) when moving to another coq project when there are many coq projects e.g. like in coq gym.

related: https://stackoverflow.com/questions/72586352/what-is-the-best-practice-for-installing-external-dependencies-in-a-coq-project/72586879#72586879

**Comment by HazardousPeach** [comment]
Opam switches are your friend here. The best way to associate them with particular projects is probably local switches https://opam.ocaml.org/blog/opam-local-switches/ . That will allow you to create an opam environment specific to your project, install any projects you need for that project, and easily switch to and away from that project. Once you've set that up in your opam, coq_serapy provides a `set_switch` function which will set the python environment to any switch, local or otherwise, as long as you pass the correct name.
